### ISSUE TITLE
This is working on cordova/phonegap?

### ISSUE THREAD

**Issue by epworthhh** [Ciul/angular-facebook#108]
Hi, i tried to use facebook javascript+angular sdk to have a login from facebook in my app.
In webapp works, but in my mobile with phonegap not work.

u could this working with phoengap/cordova? or should i do more things?

ty so much

**Comment by Ciul** [comment]
No, I love to work with cordova+ionic and I have to say that no, it doesn't work on it. Why, because you need authentication with the native facebook app when you are on a device, not the web api.

Option 1: You should try the phonegap facebook connect plugin, I've used it and works fine :)
Option 2: You may also take a look at ng-cordova/facebook plugin: http://ngcordova.com/docs/plugins/facebook/
Option 3: Some web data storage services offers services such as social login, e.g. parse.com

Hope this helps for you.
