### ISSUE TITLE
Is this library even maintained?

### ISSUE THREAD

**Issue by pbassut** [Ciul/angular-facebook#117]
- Last commit was 3 months ago
- a lot of issues open with no response
- sample application is broken

If so, please let us know in the README.

**Comment by luiscarlosjayk** [comment]
Hi @pbassut, I started this repo once I needed facebook integration with angular, and also as a way fro me to learn angular. From time to time I come to help but I haven't needed implement facebook integration recently since now I'm dedicated to CRM and other developments.
But I let this repo Open for anyone who wants to contribute to do it.

Facebook API changes constantly, that's why samples and code shall need constant care and love too.

Take into account that I don't get any benefit from this, thus, it's not truly a priority for me, but again, you can help update the code if you feel you can contribute.

Regards,
Luis
